services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: ecommerce
      DB_SSLMODE: disable
      JWT_SECRET: production-secret-key-change-this
      JWT_EXPIRE: 168h
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      ENVIRONMENT: development
  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - postgres
      # - redis
      - user-service
    ports:
      - "8082:8082"
    environment:
      PORT: "8082"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: ecommerce
      DB_SSLMODE: disable
      JWT_SECRET: production-secret-key-change-this
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      USER_SERVICE_URL: http://user-service:8081

volumes:
  pgdata:
  redisdata: